# Generated by Django 5.1.3 on 2024-12-04 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscitech_academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.TextField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uscitech_academy.gradeclasse')),
            ],
        ),
    ]
