# Generated by Django 5.1.4 on 2024-12-11 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uscitech_academy', '0004_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
